management:
  server:
    port: 8188
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.dces.report
  show-actuator: true
  api-docs:
    path: /dces-report-service
    enabled: true

services:
  maat-api:
    baseUrl: https://maat-cd-api.dev.legalservices.gov.uk/api/internal/v1
    registrationId: maatapi
    oAuthEnabled: true
    maxBufferSize: 16

emailClient:
  notify:
    key: dces_service-e696f564-9692-4c1c-81fc-77e4954ecbc9-11c1dbf1-f542-46d2-a278-7fa3841a80da #${NOTIFY_KEY}
    template-id: bd605f8d-3cc5-423f-95fb-6465535a452a #${NOTIFY_TEMPLATEID}
    recipient: victor.olorunleye@digital.justice.gov.uk
    environment: development

spring:
  mvc:
    format:
      date: dd.MM.yyyy
  security:
    oauth2:
      # Interactive/Web user authentication
      client:
        provider:
          maatapi:
            token-uri: https://maat-cd-api-dev.auth.eu-west-2.amazoncognito.com/oauth2/token
        registration:
          maatapi:
            client-id: 8s4ui1o5gq3dt49d5dfkjs54h
            client-secret: 1f4vlht03f0n7o2foaan28tlqk83d1od4ntvo17npb81grj8r3fe
            authorization-grant-type: client_credentials
            scope:
              - maat-cd-api/standard
  scheduling:
    enabled: true
    contributions:
      cron: "0-30/16 */5 * * * ?"
    fdc:
      cron: "31-59/15 */5 * * * ?"

sentry:
  debug: off
  dsn: https://cda1d7406f2ac58d5484fbbcea12d22c@o345774.ingest.sentry.io/4505674155753472
  traces-sample-rate: 1.0
  environment: dev
  release: 1.0.0
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: false
  sample-rate: 0.05
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  in-app-includes: uk.gov.justice.laa.crime.dces.report
