{{- if .Values.actuator.metrics.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "laa-dces-report-service.fullname" . }}-monitoring
  labels:
    {{- include "laa-dces-report-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "laa-dces-report-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            component: monitoring
{{- end }}