services:
  app:
    environment:
      - HOST_ENV=local
      - DECS_ADAPTOR_RESOURCE_SERVER_ISSUER_URI=
      - NOTIFY_RECIPIENT=test@example.com
      - DCES_CRON_ENABLED=true
      - DCES_CRON_CONTRIBUTIONS_MONTHLY=0 0 9-18 * * ?
      - DCES_CRON_FDC_MONTHLY=0 2 9-18 * * ?
      - DCES_CRON_CONTRIBUTIONS_DAILY=0 4 9-18 * * ?
      - DCES_CRON_FDC_DAILY=0 6 9-18 * * ?
      - LAA_DCES_REPORT_SERVICE_SERVICE_PORT_HTTP=8089
      - FEATURE_RUNDAILYREPORT=false
    env_file: app.env

    ports:
      - "8081:8081"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081 -jar app.jar