#!/bin/sh
REPORT_TITLE=$1
REPORT_DATE=$2

API_PORT=$(printenv LAA_DCES_REPORT_SERVICE_SERVICE_PORT_HTTP)

API_ENDPOINT="api/internal/v1/dces/report/failures"
REQUEST_URI="localhost:${API_PORT}/$API_ENDPOINT/$REPORT_TITLE/$REPORT_DATE"

echo "$REQUEST_URI"
curl -G $REQUEST_URI -i